### ISSUE TITLE
Build should fail if there are multiple lsp jars

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/vscode-lingua-franca#148]
When I run `npm install` on the current master, then the resulting `lib` directory is empty. Consequently, the generated *.vsix is broken and the extension cannot start the language server. I also noticed that the resulting extension is called `vscode-lingua-franca-0.5.1.vsix` despite the recent 0.6.0 release.

**Comment by cmnrd** [comment]
Now I noticed the error message in npm's output:
```
Error: Multiple matches to /home/cmenard/projects/lf/vscode-lingua-franca/lingua-franca/lsp/build/libs/lsp-+(?).+(?).+(?)?(-SNAPSHOT)-all.jar were found. Please delete the jars that you do not want to use.
    at copyJar (/home/cmenard/projects/lf/vscode-lingua-franca/src/build_lds.ts:48:15)
    at build (/home/cmenard/projects/lf/vscode-lingua-franca/src/build_lds.ts:130:9)
```
I deleted the jars and now it works fine.

Would be great if npm actually fails if there is an error.

**Comment by cmnrd** [comment]
The created artifact is still called `vscode-lingua-franca-0.5.1.vsix`

**Comment by lhstrh** [comment]
Just tried to reproduce, but it works just fine on my end. Did you pull the latest and updated submodules recursively?

![image](https://github.com/lf-lang/vscode-lingua-franca/assets/19938940/fde949eb-8c5f-4731-8212-9edcd632363c)

**Comment by cmnrd** [comment]
Ok, looks like something went wrong when I pulled. I had not checked out the latest main before... Sorry for the noise!

So this issue breaks down to npm not failing in case there are multiple lsp jars. While it prints
```
Error: Multiple matches to /home/cmenard/projects/lf/vscode-lingua-franca/lingua-franca/lsp/build/libs/lsp-+(?).+(?).+(?)?(-SNAPSHOT)-all.jar were found. Please delete the jars that you do not want to use.
    at copyJar (/home/cmenard/projects/lf/vscode-lingua-franca/src/build_lds.ts:48:15)
    at build (/home/cmenard/projects/lf/vscode-lingua-franca/src/build_lds.ts:130:9)
```
This is easily missed as the overall build succeeds.
