### ISSUE TITLE
Diagrams not working in VS Code

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/vscode-lingua-franca#52]
When I use File->Open in VS code to open an LF file, the diagrams sometimes remain blank, as shown in the screen dump below. There seems to be no way to get them to appear.  Also, there is no "show all details" button as in Epoch, which means that when diagrams do get rendered, they are stuck at the top-level view.  Clicking on the reactors in the diagram has no effect.

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/8513334/167808618-0df14aad-65ee-4822-85fd-69ae25337d41.png">

**Comment by petervdonovan** [comment]
I have encountered this behavior accompanied by this error message (in `View` -> `Output` -> `LF Language Server`):
```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Composite
	at de.cau.cs.kieler.klighd.standalone.KlighdStandaloneSetup.doInitialize(KlighdStandaloneSetup.java:69)
	at de.cau.cs.kieler.klighd.standalone.KlighdStandaloneSetup.initialize(KlighdStandaloneSetup.java:42)
	at de.cau.cs.kieler.klighd.lsp.launch.AbstractLsCreator.buildAndStartLS(AbstractLsCreator.java:117)
	at de.cau.cs.kieler.klighd.lsp.launch.LanguageServerLauncher.start(LanguageServerLauncher.java:63)
	at org.eclipse.xtext.ide.server.ServerLauncher.launch(ServerLauncher.java:48)
	at de.cau.cs.kieler.klighd.lsp.launch.LanguageServerLauncher.launch(LanguageServerLauncher.java:52)
	at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.run(AbstractLanguageServer.java:203)
	at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer$1.run(AbstractLanguageServer.java:90)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Composite
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 9 more
```

However, when I rebuilt from `master`, the error was gone.

Before the next release, maybe we should reassess whether this issue still exists for anyone.

**Comment by lhstrh** [comment]
It is assumed that with the new version of KLighD this issue is resolved. Feel free to reopen if this is somehow not the case.
